export const allUpcomingMatches = [
  {
    _id: '6568418709303c7095be33e8',
    matchType: 'International',
    seriesName: 'Australia tour of India, 2023',
    seriesId: 7233,
    matchId: 82462,
    matchDesc: '4th T20I',
    matchFormat: 'T20',
    startDate: 1701437400000,
    endDate: 1701450000000,
    state: 'Upcoming',
    status: 'Match starts at Dec 01, 13:30 GMT',
    team1: {
      teamId: 2,
      teamName: 'India',
      teamSName: 'IND',
      imageId: 172115,
      imageLink: 'https://demo.sitegenio.in/api/v1/static/c172115.jpg',
    },
    team2: {
      teamId: 4,
      teamName: 'Australia',
      teamSName: 'AUS',
      imageId: 172117,
      imageLink: 'https://demo.sitegenio.in/api/v1/static/c172117.jpg',
    },
    venueInfo: {
      id: 335,
      ground: 'Shaheed Veer Narayan Singh International Stadium',
      city: 'Raipur',
      timezone: '+05:30',
      latitude: '21.203523',
      longitude: '81.823929',
    },
    megaPrize: 100000,
    timestamp: '2023-11-30 13:32:15',
    isDeleted: false,
    createdAt: '2023-11-30T08:02:15.042Z',
    updatedAt: '2023-11-30T08:02:16.184Z',
    __v: 0,
  },
  {
    _id: '6568418709303c7095be33ea',
    matchType: 'Domestic',
    seriesName: 'Vijay Hazare Trophy 2023',
    seriesId: 6722,
    matchId: 75077,
    matchDesc: 'Round 5, Group D',
    matchFormat: 'ODI',
    startDate: 1701401400000,
    endDate: 1701430200000,
    state: 'Upcoming',
    status: 'Match starts at Dec 01, 03:30 GMT',
    team1: {
      teamId: 162,
      teamName: 'Assam',
      teamSName: 'ASM',
      imageId: 172230,
      imageLink: 'https://demo.sitegenio.in/api/v1/static/c172230.jpg',
    },
    team2: {
      teamId: 93,
      teamName: 'Uttar Pradesh',
      teamSName: 'UP',
      imageId: 172185,
      imageLink: 'https://demo.sitegenio.in/api/v1/static/c172185.jpg',
    },
    venueInfo: {
      id: 120,
      ground: 'Sector 16 Stadium',
      city: 'Chandigarh',
      timezone: '+05:30',
      latitude: '30.741797',
      longitude: '76.774915',
    },
    megaPrize: 100000,
    timestamp: '2023-11-30 13:32:15',
    isDeleted: false,
    createdAt: '2023-11-30T08:02:15.442Z',
    updatedAt: '2023-11-30T08:02:16.967Z',
    __v: 0,
  },
];

export const carousalItems = [
  {
    __v: 0,
    _id: '6568446fb247fcb7fcbb929e',
    addUrl: 'https://google.com',
    imageLink:
      'https://demo.sitegenio.in/api/v1/static/Screenshot 2023-10-19 192301.png',
    timestamp: '2023-11-30 13:44:39',
    title: 'Random add',
    type: 'ADDVERTISMENT',
  },
];

export const MatchPool = [
  {
    _id: '65675b5d8c6ce05a959b7867',
    matchId: 82462,
    type: 'MEGA',
    prizePool: 100000,
    entryFee: 50,
    totalPlayersToJoin: 100,
    firstPrize: 25000,
    winnerPercentage: 50,
    teamsPerUser: 1,
    timestamp: '2023-11-29 21:10:13',
    __v: 0,
  },
  {
    _id: '65675b5d8c6ce05a959b7869',
    matchId: 82462,
    type: 'HIGH RETURN',
    prizePool: 20000,
    entryFee: 20,
    totalPlayersToJoin: 100,
    firstPrize: 5000,
    winnerPercentage: 55,
    teamsPerUser: 1,
    timestamp: '2023-11-29 21:10:13',
    __v: 0,
  },
  {
    _id: '65675b5d8c6ce05a959b786b',
    matchId: 82462,
    type: 'LOW RETURN',
    prizePool: 20000,
    entryFee: 15,
    totalPlayersToJoin: 100,
    firstPrize: 3500,
    winnerPercentage: 57,
    teamsPerUser: 1,
    timestamp: '2023-11-29 21:10:13',
    __v: 0,
  },
  {
    _id: '65675b5d8c6ce05a959b786d',
    matchId: 82462,
    type: 'PRACTICE',
    prizePool: 0,
    entryFee: 0,
    totalPlayersToJoin: 100,
    firstPrize: 0,
    winnerPercentage: 0,
    teamsPerUser: 1,
    timestamp: '2023-11-29 21:10:13',
    __v: 0,
  },
];

export const MatchPoolData = [
  {
    title: 'Practice',
    data: [
      {
        _id: '65675b5d8c6ce05a959b786d',
        matchId: 82462,
        prizePool: 0,
        entryFee: 0,
        totalPlayersToJoin: 100,
        firstPrize: 0,
        winnerPercentage: 0,
        teamsPerUser: 1,
        timestamp: '2023-11-29 21:10:13',
        __v: 0,
      },
    ],
  },
  {
    title: 'LOW RETURN',
    data: [
      {
        _id: '65675b5d8c6ce05a959b786d',
        matchId: 82462,
        prizePool: 0,
        entryFee: 0,
        totalPlayersToJoin: 100,
        firstPrize: 0,
        winnerPercentage: 0,
        teamsPerUser: 1,
        timestamp: '2023-11-29 21:10:13',
        __v: 0,
      },
    ],
  },
];

const data = {
  _v: 0,
  _id: '6575683047a3f7a17c3509a9',
  entryFee: 20,
  match: {
    _v: 0,
    _id: '6574b234695fffbdc7873d0f',
    createdAt: '2023-12-09T18:30:12.926Z',
    endDate: 1702294200000,
    isDeleted: false,
    matchDesc: '1st quarter final',
    matchFormat: 'ODI',
    matchId: 75371,
    matchType: 'Domestic',
    megaPrize: 100000,
    seriesId: 6722,
    seriesName: 'Vijay Hazare Trophy 2023',
    startDate: 1702265400000,
    state: 'Upcoming',
    status: 'Match starts at Dec 11, 03:30 GMT',
    team1: {
      imageId: 172260,
      imageLink: 'https://demo.sitegenio.in/api/v1/static/c172260.jpg',
      teamId: 200,
      teamName: 'Haryana',
      teamSName: 'HAR',
    },
    team2: {
      imageId: 172285,
      imageLink: 'https://demo.sitegenio.in/api/v1/static/c172285.jpg',
      teamId: 232,
      teamName: 'Bengal',
      teamSName: 'BEN',
    },
    timestamp: '2023-12-10 00:00:12',
    updatedAt: '2023-12-10T18:30:11.215Z',
    venueInfo: {
      city: 'Rajkot',
      ground: 'Saurashtra Cricket Association Stadium',
      id: 290,
      latitude: '22.289721',
      longitude: '70.793182',
      timezone: '+05:30',
    },
  },
  matchStatus: 'Live',
  mobile: 9504141640,
  poolId: '6574b234695fffbdc7873d13',
  score: 0,
  team: '6575682d47a3f7a17c350997',
  timestamp: '2023-12-10 12:56:40',
  userUid: 'H3UDSI1XEF',
  winnings: 0,
};

export const ScorecardData = {
  _id: '6571b834260670f09334699d',
  matchId: 82462,
  status: 'India won by 20 runs',
  tossResult: {
    tossWinnerName: 'Australia',
    decision: 'Bowling',
  },
  playersOfTheMatch: [
    {
      fullName: 'Axar Patel',
      teamName: 'India',
      faceImageId: 332897,
      image: 'http://localhost:5000/api/v1/static/c332897.jpg',
    },
  ],
  inningsOne: {
    batTeamName: 'India',
    batTeamShortName: 'IND',
    battingData: [
      {
        serialNo: 1,
        status: 'Bat',
        playerId: 13940,
        name: 'Yashasvi Jaiswal',
        isCaptain: false,
        isKeeper: false,
        runs: 37,
        balls: 28,
        fours: 6,
        sixes: 1,
        strikeRate: 132.14,
        outDesc: 'c Ben McDermott b Aaron Hardie',
      },
      {
        serialNo: 2,
        status: 'Bat',
        playerId: 11813,
        name: 'Ruturaj Gaikwad',
        isCaptain: false,
        isKeeper: false,
        runs: 32,
        balls: 28,
        fours: 3,
        sixes: 1,
        strikeRate: 114.29,
        outDesc: 'c Dwarshuis b T Sangha',
      },
      {
        serialNo: 3,
        status: 'Bat',
        playerId: 9428,
        name: 'Shreyas Iyer',
        isCaptain: false,
        isKeeper: false,
        runs: 8,
        balls: 7,
        fours: 0,
        sixes: 0,
        strikeRate: 114.29,
        outDesc: 'c Chris Green b T Sangha',
      },
      {
        serialNo: 4,
        status: 'Bat',
        playerId: 7915,
        name: 'Suryakumar Yadav',
        isCaptain: true,
        isKeeper: false,
        runs: 1,
        balls: 2,
        fours: 0,
        sixes: 0,
        strikeRate: 50,
        outDesc: 'c Wade b Dwarshuis',
      },
      {
        serialNo: 5,
        status: 'Bat',
        playerId: 10896,
        name: 'Rinku Singh',
        isCaptain: false,
        isKeeper: false,
        runs: 46,
        balls: 29,
        fours: 4,
        sixes: 2,
        strikeRate: 158.62,
        outDesc: 'lbw b Behrendorff',
      },
      {
        serialNo: 6,
        status: 'Bat',
        playerId: 10214,
        name: 'Jitesh Sharma',
        isCaptain: false,
        isKeeper: true,
        runs: 35,
        balls: 19,
        fours: 1,
        sixes: 3,
        strikeRate: 184.21,
        outDesc: 'c Head b Dwarshuis',
      },
      {
        serialNo: 7,
        status: 'Bat',
        playerId: 8808,
        name: 'Axar',
        isCaptain: false,
        isKeeper: false,
        runs: 0,
        balls: 1,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
        outDesc: 'c T Sangha b Dwarshuis',
      },
      {
        serialNo: 8,
        status: 'Bat',
        playerId: 7836,
        name: 'D Chahar',
        isCaptain: false,
        isKeeper: false,
        runs: 0,
        balls: 2,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
        outDesc: 'c Chris Green b Behrendorff',
      },
      {
        serialNo: 9,
        status: 'Bat',
        playerId: 14659,
        name: 'Ravi Bishnoi',
        isCaptain: false,
        isKeeper: false,
        runs: 4,
        balls: 3,
        fours: 0,
        sixes: 0,
        strikeRate: 133.33,
        outDesc: 'run out (Philippe/Head)',
      },
      {
        serialNo: 10,
        status: 'Bat',
        playerId: 9781,
        name: 'Avesh Khan',
        isCaptain: false,
        isKeeper: false,
        runs: 1,
        balls: 1,
        fours: 0,
        sixes: 0,
        strikeRate: 100,
        outDesc: 'not out',
      },
      {
        serialNo: 11,
        status: 'Did not Bat',
        playerId: 10754,
        name: 'Mukesh Kumar',
        isCaptain: false,
        isKeeper: false,
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
        outDesc: '',
      },
    ],
    bowlTeamName: 'Australia',
    bowlTeamShortName: 'AUS',
    bowlingData: [
      {
        serialNo: 1,
        playerId: 13170,
        name: 'Aaron Hardie',
        isCaptain: false,
        isKeeper: false,
        overs: 3,
        maidens: 1,
        runs: 20,
        wickets: 1,
        economy: 6.7,
      },
      {
        serialNo: 2,
        playerId: 7773,
        name: 'Behrendorff',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 32,
        wickets: 2,
        economy: 8,
      },
      {
        serialNo: 3,
        playerId: 9739,
        name: 'Dwarshuis',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 40,
        wickets: 3,
        economy: 10,
      },
      {
        serialNo: 4,
        playerId: 10162,
        name: 'Chris Green',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 36,
        wickets: 0,
        economy: 9,
      },
      {
        serialNo: 5,
        playerId: 15137,
        name: 'T Sangha',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 30,
        wickets: 2,
        economy: 7.5,
      },
      {
        serialNo: 6,
        playerId: 9456,
        name: 'Matthew Short',
        isCaptain: false,
        isKeeper: false,
        overs: 1,
        maidens: 0,
        runs: 10,
        wickets: 0,
        economy: 10,
      },
    ],
    scoreDetails: {
      runs: 174,
      wickets: 9,
      runRate: 8.7,
      overs: 20,
    },
    extrasDetails: {
      noBalls: 0,
      wides: 4,
      byes: 4,
      legByes: 2,
      penalty: 0,
      total: 10,
    },
    fallOfWickets: [
      {
        serialNo: 1,
        name: 'Yashasvi Jaiswal',
        wktNbr: 1,
        wktOver: 5.6,
        wktRuns: 50,
      },
      {
        serialNo: 2,
        name: 'Shreyas Iyer',
        wktNbr: 2,
        wktOver: 7.5,
        wktRuns: 62,
      },
      {
        serialNo: 3,
        name: 'Suryakumar Yadav',
        wktNbr: 3,
        wktOver: 8.1,
        wktRuns: 63,
      },
      {
        serialNo: 4,
        name: 'Ruturaj Gaikwad',
        wktNbr: 4,
        wktOver: 13.2,
        wktRuns: 111,
      },
      {
        serialNo: 5,
        name: 'Jitesh Sharma',
        wktNbr: 5,
        wktOver: 18.4,
        wktRuns: 167,
      },
      {
        serialNo: 6,
        name: 'Axar',
        wktNbr: 6,
        wktOver: 18.5,
        wktRuns: 168,
      },
      {
        serialNo: 7,
        name: 'Rinku Singh',
        wktNbr: 7,
        wktOver: 19.1,
        wktRuns: 168,
      },
      {
        serialNo: 8,
        name: 'D Chahar',
        wktNbr: 8,
        wktOver: 19.3,
        wktRuns: 169,
      },
      {
        serialNo: 9,
        name: 'Ravi Bishnoi',
        wktNbr: 9,
        wktOver: 20,
        wktRuns: 174,
      },
    ],
  },

  inningsTwo: {
    batTeamName: 'Australia',
    batTeamShortName: 'AUS',
    battingData: [
      {
        serialNo: 1,
        status: 'Bat',
        playerId: 8497,
        name: 'Travis Head',
        isCaptain: false,
        isKeeper: false,
        runs: 31,
        balls: 16,
        fours: 5,
        sixes: 1,
        strikeRate: 193.75,
        outDesc: 'c Mukesh Kumar b Axar',
      },
      {
        serialNo: 2,
        status: 'Bat',
        playerId: 13172,
        name: 'Josh Philippe',
        isCaptain: false,
        isKeeper: false,
        runs: 8,
        balls: 7,
        fours: 2,
        sixes: 0,
        strikeRate: 114.29,
        outDesc: 'b Ravi Bishnoi',
      },
      {
        serialNo: 3,
        status: 'Bat',
        playerId: 9453,
        name: 'Ben McDermott',
        isCaptain: false,
        isKeeper: false,
        runs: 19,
        balls: 22,
        fours: 1,
        sixes: 0,
        strikeRate: 86.36,
        outDesc: 'b Axar',
      },
      {
        serialNo: 4,
        status: 'Bat',
        playerId: 13170,
        name: 'Aaron Hardie',
        isCaptain: false,
        isKeeper: false,
        runs: 8,
        balls: 9,
        fours: 1,
        sixes: 0,
        strikeRate: 88.89,
        outDesc: 'b Axar',
      },
      {
        serialNo: 5,
        status: 'Bat',
        playerId: 13169,
        name: 'Tim David',
        isCaptain: false,
        isKeeper: false,
        runs: 19,
        balls: 20,
        fours: 0,
        sixes: 1,
        strikeRate: 95,
        outDesc: 'c Yashasvi Jaiswal b D Chahar',
      },
      {
        serialNo: 6,
        status: 'Bat',
        playerId: 9456,
        name: 'Matthew Short',
        isCaptain: false,
        isKeeper: false,
        runs: 22,
        balls: 19,
        fours: 2,
        sixes: 1,
        strikeRate: 115.79,
        outDesc: 'c Yashasvi Jaiswal b D Chahar',
      },
      {
        serialNo: 7,
        status: 'Bat',
        playerId: 1649,
        name: 'Matthew Wade',
        isCaptain: true,
        isKeeper: true,
        runs: 36,
        balls: 23,
        fours: 2,
        sixes: 2,
        strikeRate: 156.52,
        outDesc: 'not out',
      },
      {
        serialNo: 8,
        status: 'Bat',
        playerId: 9739,
        name: 'Ben Dwarshuis',
        isCaptain: false,
        isKeeper: false,
        runs: 1,
        balls: 2,
        fours: 0,
        sixes: 0,
        strikeRate: 50,
        outDesc: 'b Avesh Khan',
      },
      {
        serialNo: 9,
        status: 'Bat',
        playerId: 10162,
        name: 'Chris Green',
        isCaptain: false,
        isKeeper: false,
        runs: 2,
        balls: 3,
        fours: 0,
        sixes: 0,
        strikeRate: 66.67,
        outDesc: 'not out',
      },
      {
        serialNo: 10,
        status: 'Did not Bat',
        playerId: 7773,
        name: 'Jason Behrendorff',
        isCaptain: false,
        isKeeper: false,
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
        outDesc: '',
      },
      {
        serialNo: 11,
        status: 'Did not Bat',
        playerId: 15137,
        name: 'Tanveer Sangha',
        isCaptain: false,
        isKeeper: false,
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
        outDesc: '',
      },
    ],
    bowlTeamName: 'India',
    bowlTeamShortName: 'IND',
    bowlingData: [
      {
        serialNo: 1,
        playerId: 7836,
        name: 'Deepak Chahar',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 44,
        wickets: 2,
        economy: 11,
      },
      {
        serialNo: 2,
        playerId: 10754,
        name: 'Mukesh Kumar',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 42,
        wickets: 0,
        economy: 10.5,
      },
      {
        serialNo: 3,
        playerId: 14659,
        name: 'Ravi Bishnoi',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 17,
        wickets: 1,
        economy: 4.2,
      },
      {
        serialNo: 4,
        playerId: 8808,
        name: 'Axar Patel',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 16,
        wickets: 3,
        economy: 4,
      },
      {
        serialNo: 5,
        playerId: 9781,
        name: 'Avesh Khan',
        isCaptain: false,
        isKeeper: false,
        overs: 4,
        maidens: 0,
        runs: 33,
        wickets: 1,
        economy: 8.2,
      },
    ],
    scoreDetails: {
      runs: 154,
      wickets: 7,
      runRate: 7.7,
      overs: 20,
    },
    extrasDetails: {
      noBalls: 1,
      wides: 5,
      byes: 0,
      legByes: 2,
      penalty: 0,
      total: 8,
    },
    fallOfWickets: [
      {
        serialNo: 1,
        name: 'Josh Philippe',
        wktNbr: 1,
        wktOver: 3.1,
        wktRuns: 40,
      },
      {
        serialNo: 2,
        name: 'Travis Head',
        wktNbr: 2,
        wktOver: 4.4,
        wktRuns: 44,
      },
      {
        serialNo: 3,
        name: 'Aaron Hardie',
        wktNbr: 3,
        wktOver: 6.2,
        wktRuns: 52,
      },
      {
        serialNo: 4,
        name: 'Ben McDermott',
        wktNbr: 4,
        wktOver: 11.2,
        wktRuns: 87,
      },
      {
        serialNo: 5,
        name: 'Tim David',
        wktNbr: 5,
        wktOver: 14.4,
        wktRuns: 107,
      },
      {
        serialNo: 6,
        name: 'Matthew Short',
        wktNbr: 6,
        wktOver: 16.4,
        wktRuns: 126,
      },
      {
        serialNo: 7,
        name: 'Ben Dwarshuis',
        wktNbr: 7,
        wktOver: 17.3,
        wktRuns: 133,
      },
    ],
  },
  createdAt: '2023-12-07T12:19:00.318Z',
  updatedAt: '2023-12-07T12:19:00.318Z',
  __v: 0,
};

const abc = {
  __v: 0,
  _id: '657eaebdd3bf7c18598ae66c',
  createdAt: '2023-12-17T08:18:05.220Z',
  endDate: 1702986300000,
  isDeleted: false,
  isLineupOut: true,
  matchDesc: '8th Match',
  matchFormat: 'T20',
  matchId: 76731,
  matchType: 'League',
  megaPrize: 100000,
  seriesId: 6822,
  seriesName: 'Big Bash League 2023-24',
  startDate: 1702973700000,
  state: 'Upcoming',
  status: 'Match starts at Dec 19, 08:15 GMT',
  team1: {
    imageId: 172259,
    imageLink: 'https://demo.sitegenio.in/api/v1/static/c172259.jpg',
    teamId: 199,
    teamName: 'Adelaide Strikers',
    teamSName: 'ADS',
  },
  team2: {
    imageId: 172252,
    imageLink: 'https://demo.sitegenio.in/api/v1/static/c172252.jpg',
    teamId: 192,
    teamName: 'Sydney Thunder',
    teamSName: 'SYT',
  },
  timestamp: '2023-12-17 13:48:05',
  updatedAt: '2023-12-19T05:02:01.685Z',
  venueInfo: {
    city: 'Adelaide',
    ground: 'Adelaide Oval',
    id: 40,
    latitude: '-34.915516',
    longitude: '138.596115',
    timezone: '+10:30',
  },
};
